# Generated by Django 3.0.3 on 2020-05-16 04:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikeRecode',
            new_name='LikeRecord',
        ),
        migrations.RemoveField(
            model_name='likecount',
            name='like_num',
        ),
        migrations.AddField(
            model_name='likecount',
            name='liked_num',
            field=models.IntegerField(default=0),
        ),
    ]
