# Generated by Django 3.0.3 on 2020-05-16 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200516_1224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likerecord',
            old_name='like_time',
            new_name='liked_time',
        ),
    ]
