# Generated by Django 3.0.3 on 2020-04-22 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200422_1006'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
